FROM ghcr.io/astral-sh/uv:alpine
WORKDIR /app

COPY . .

# Install dependencies
RUN uv sync


RUN if [ "$USE_CRAWL4AI" = "False" ] || [ "$USE_CRAWL4AI" = "false" ]; then \
    echo "Removing crawl4ai from dependencies..."; \
    sed -i '/^[[:space:]]*"crawl4ai[>=,~^].*",$/d' pyproject.toml; \
    fi

RUN mkdir -p /app/sandbox
# Run the application on port 8501
EXPOSE 8501

# Run the application
CMD ["uv", "run", "streamlit", "run", "main.py"]
