FROM ghcr.io/astral-sh/uv:alpine
WORKDIR /app

COPY . .

# Install dependencies
RUN uv sync

RUN mkdir -p /app/sandbox
# Run the application on port 8501
EXPOSE 8501

# Run the application
CMD ["uv", "run", "streamlit", "run", "main.py"]
